# Generated by Django 4.2 on 2024-05-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='flan_uuid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='flan',
            name='is_private',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='flan',
            name='slug',
            field=models.SlugField(),
        ),
    ]
