# Generated by Django 4.2 on 2024-05-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_flan_flan_uuid_alter_flan_is_private_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_form_uuid', models.UUIDField()),
                ('customer_name', models.CharField(max_length=64)),
                ('customer_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
