# Generated by Django 4.2 on 2024-06-09 19:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_flan_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flan',
            name='flan_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
